# Generated by Django 5.1.3 on 2024-11-18 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.PositiveIntegerField()),
                ('course', models.CharField(max_length=100)),
                ('profile_picture', models.ImageField(upload_to='profile_images')),
            ],
        ),
    ]
